version: "3.8"
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    restart: always
    ports:
      - 2181:2181
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"

  kafka:
    image: wurstmeister/kafka:latest
    restart: always
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_CREATE_TOPICS: "demo:1:1"
    depends_on:
      - zookeeper

  kowl:
    image: quay.io/cloudhut/kowl:master
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      KAFKA_BROKERS: kafka:9092
      CONNECT_ENABLED: true
      CONNECT_CLUSTERS_NAME: localhost
      CONNECT_CLUSTERS_URL: http://connect:8083

  connect:
    container_name: debezium
    image: debezium/connect:1.6
    ports:
      - 8083:8083
    links:
      - kafka
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - CONFIG_STORAGE_TOPIC=connect_config
      - OFFSET_STORAGE_TOPIC=connect_offset
      - STATUS_STORAGE_TOPIC=connect_status
      - CONNECT_TOPIC_CREATION_DEFAULT_PARTITIONS=10
