version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
    # Run the postgres-init.sql query in your local to setup your database
    volumes:
    - ./postgres-init.sql:/docker-entrypoint-initdb.d/init.sql
  
